### PR TITLE
Wrap action trigger in scope.$apply

### PR DESCRIPTION
**Pull request by jfedyczak**
`scroll-trigger` call isn't wrapped in scope.$apply - this disables all the angular's magic. This commit fixes that, but this may be a breaking change if someone already added $scope.apply manually, so I think major version needs bumping to comply with SEMVER... or maybe not since it's a 0 (beta) version :)

### CODE REVIEW

**Comment by princemaple** [comment]
Hi, I'm out traveling without my laptop at the moment. I'll review the implementation in a couple days. Ping me if I don't get back to you by 2nd of March.

**Comment by princemaple** [comment]
Thanks BTW

**Comment by princemaple** [comment]
Hi @jfedyczak , I'll probably leave this as is. I wrote this library because I wanted a scrolling library that is low level enough that the users can have full control of the scrolling action, including whether to call `apply`. It's not the case that we always want to call `apply` after a scrolling event is handled, e.g. when we merely want to set the `src` of an `img`. Hence, when invoking the digest cycle is an intended behavior, the user of the library should explicitly do so in the `action`. Alternatively, we can add one more directive that explicitly enables `apply`.

**Comment by jfedyczak** [comment]
Fair enough. But the need of using `$apply` seems very low-level to me and in my opinion should only occur when there is interaction between angular and non-angular code and I believe that it should be hidden and transparent for end-user of the library. But, considering performance issues, maybe separate handler is the way to go.

**Comment by princemaple** [comment]
> But, considering performance issues, maybe separate handler is the way to go.

Exactly.

Hopefully, Angular 2 solves most of the problems. If I was to port this library to ng2, I probably wouldn't need to worry about the side effects of `action` to cause performance issues. To be honest, not having to explicitly call `apply` is a bigger win IMHO than the performance improvements for this particular, DOM / interaction heavy, kind of library.

**Pull request closed without merging**
